- name: Install Java 21 on Windows machines
  hosts: all
  tasks:
    - name: Ensure C:\Temp directory exists
      win_file:
        path: C:\Temp
        state: directory

    - name: Download Java 21 installer
      win_get_url:
        url: https://download.oracle.com/java/21/latest/jdk-21_windows-x64_bin.exe
        dest: C:\Temp\jdk-21_windows-x64_bin.exe

    - name: Install Java 21
      win_shell: C:\Temp\jdk-21_windows-x64_bin.exe /s

    - name: Set JAVA_HOME environment variable
      win_environment:
        name: JAVA_HOME
        value: 'C:\Program Files\Java\jdk-21'
        level: machine
        state: present

    - name: Get current PATH
      win_shell: $env:Path
      register: current_path

    - name: Set updated PATH
      win_environment:
        name: Path
        value: '{{ current_path.stdout }};%JAVA_HOME%\bin'
        level: machine
        state: present
